export const SORT_COINS = "SORT_COINS";

export const FETCH_COIN_DATA = 'FETCH_COIN_DATA';
export const FETCH_COIN_DATA_SUCCESS = 'FETCH_COIN_DATA_SUCCESS';
export const FETCH_COIN_DATA_FAIL = 'FETCH_COIN_DATA_FAIL';

export const COIN_DATA_HISTORICAL = 'COIN_DATA_HISTORICAL';
export const COIN_DATA_HISTORICAL_SUCCESS = 'COIN_DATA_HISTORICAL_SUCCESS';
export const COIN_DATA_HISTORICAL_FAIL = 'COIN_DATA_HISTORICAL_FAIL';

export const FETCH_GLOBAL_DATA = 'FETCH_GLOBAL_DATA';
export const FETCH_GLOBAL_DATA_SUCCESS = 'FETCH_GLOBAL_DATA_SUCCESS';
export const FETCH_GLOBAL_DATA_FAIL = 'FETCH_GLOBAL_DATA_FAIL';

export const FETCH_DB_DATA = 'FETCH_DB_DATA';
export const FETCH_DB_DATA_SUCCESS = 'FETCH_DB_DATA_SUCCESS';
export const FETCH_DB_DATA_FAIL = 'FETCH_DB_DATA_FAIL';

export const CREATE_TABLE = 'CREATE_TABLE'

export const GET_PORTFOLIOS_SUCCESS = 'GET_PORTFOLIOS_SUCCESS'
export const GET_PORTFOLIOS_FAIL = 'GET_PORTFOLIOS_FAIL'